parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads/photos'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Registra todos os serviços da pasta src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Registra controllers para injeção de dependência
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
