services:
  backend:
    build:
      context: ./backend
    container_name: bandscloud-backend
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: bandscloud-frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "5173:5173"

  db:
    image: mysql:8.0
    container_name: bandscloud-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bandscloud
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
