services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bandscloud-backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html:cached
    expose:
      - "9000"
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: '3ddafd74a7ec86feb60e2747257534b7ee64fc6862112aa2cf78055416e603d3'
      DATABASE_URL: 'mysql://symfony:symfony@db:3306/bandscloud?serverVersion=8.0.32&charset=utf8mb4'
      JWT_SECRET_KEY: /var/www/html/config/jwt/private.pem
      JWT_PUBLIC_KEY: /var/www/html/config/jwt/public.pem
      JWT_PASSPHRASE: 'Z7m@Pq9!Xw2#Rf4$'
    depends_on:
      - db
    networks:
      - bandscloud-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bandscloud-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8081/api
    networks:
      - bandscloud-network

  db:
    image: mysql:8.0
    container_name: bandscloud-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bandscloud
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bandscloud-network

  nginx:
    image: nginx:latest
    container_name: bandscloud-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
      - ./backend/public:/var/www/html/public:ro
    depends_on:
      - backend
      - frontend
    networks:
      - bandscloud-network

volumes:
  mysql_data:

networks:
  bandscloud-network:
    driver: bridge
