# docker-compose.yml
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: bandscloud-backend
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    command: php-fpm
    expose:
      - "9000"
    depends_on:
      - db
    environment:
      APP_ENV: dev
      APP_SECRET: 21a3e44f79031f3a8304d8a09123ef9a372f093df7b6ecaa7f8e4c8e5b2cda6f
      DATABASE_URL: mysql://symfony:symfony@db:3306/bandscloud?serverVersion=8.0.32&charset=utf8mb4
      JWT_SECRET_KEY: /var/www/html/config/jwt/private.pem
      JWT_PUBLIC_KEY: /var/www/html/config/jwt/public.pem
      JWT_PASSPHRASE: Z7m@Pq9!Xw2#Rf4$
      CORS_ALLOW_ORIGIN: "http://localhost:5173,https://bandscloud-frontend.onrender.com"

  frontend:
    build:
      context: ./frontend
    container_name: bandscloud-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"

  db:
    image: mysql:8.0
    container_name: bandscloud-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bandscloud
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: bandscloud-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend

volumes:
  mysql_data:
