services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - ./backend:/var/www/html:cached
    networks:
      - bandscloud-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8081/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - bandscloud-network

  db:
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bandscloud-network

  nginx:
    ports:
      - "8081:80"
    networks:
      - bandscloud-network

volumes:
  mysql_data:

networks:
  bandscloud-network:
    driver: bridge
