version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: bandscloud-backend
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: bandscloud-frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "5173:5173"

  db:
    image: mysql:8.0
    container_name: bandscloud-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bandscloud
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: bandscloud-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend

volumes:
  mysql_data:
