services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev  
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8081/api
