framework:
    secret: '%env(APP_SECRET)%'

    session:
        enabled: true

    profiler:
        enabled: '%kernel.debug%'

    router:
        utf8: true

    validation:
        enable_attributes: true
