nelmio_cors:
  defaults:
    allow_origin: ['*']
    allow_credentials: false
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Authorization']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['*']
      allow_credentials: false
      allow_headers: ['Content-Type', 'Authorization']
      expose_headers: ['Authorization']
      allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
      max_age: 3600
